api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getData),
    path('add/', views.addItem),
]

hotel/urls.py
from django.urls import path
from .views import hotel_list, create_hotel

app_name = 'hotel'

urlpatterns = [
    path('', hotel_list, name='hotel_list'),
    path('create/', create_hotel, name='create_hotel'),
]

my_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api', include('api.urls')),
    path('product/', include('api1.urls')),
    path('products/', include('second_app.urls')),
    path('datas/', include('api3.urls')),
    path('students/', include('student_api.urls')),
    path('canada/', include('canada.urls')),
    path('clinic/', include('clinic.urls')),
    path('daraja/', include('daraja_api.urls')),
    path('weather/', include('weather_app.urls')),
    path('covid19/', include('covid19.urls')),
    path('openmrs/', include('openmrs_api.urls')),
    path('pos/', include('pos.urls')),
    path('', include('dashboard.urls')),
    path('bank/', include('bank.urls')),
    path('hotel/', include('hotel.urls')),
    path('user/', include('userauths.urls')),
    
    
     
    
]

hotel/models.py
from django.db import models

class Hotel(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=255)

class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_number = models.CharField(max_length=10)
    capacity = models.IntegerField()

class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest_name = models.CharField(max_length=100)
    check_in = models.DateField()
    check_out = models.DateField()

class BookingDetail(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    service_description = models.CharField(max_length=255)

class Guest(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

class RoomServices(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    service_type = models.CharField(max_length=100)

hotel/forms.py
from django import forms
from .models import Hotel, Room, Booking

class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = '__all__'

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = '__all__'

hotel/views.py
from django.shortcuts import render, redirect
from .models import Hotel, Room, Booking
from .forms import HotelForm, RoomForm, BookingForm

def hotel_list(request):
    hotels = Hotel.objects.all()
    return render(request, 'hotel/hotel_list.html', {'hotels': hotels})

def create_hotel(request):
    if request.method == 'POST':
        form = HotelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hotel:hotel_list')
    else:
        form = HotelForm()
    return render(request, 'hotel/hotel_form.html', {'form': form})

hotel/templates/hotel/base.html
{%  load static %}

<link rel="stylesheet" href="{% static 'hotel/css/mdb.min.css' %}">
<script src="{% static 'hotel/js/mdb.min.js' %}"></script>








<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarLeftAlignExample"
      aria-controls="navbarLeftAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarLeftAlignExample">
      <!-- Left links -->


      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="">Home</a>
        </li>

        <li class="nav-item">
              <a class="nav-link text-white" href="">Announcement</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-white" href="">Herroes</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-white"   href="">Courses</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-white"   href="">About us</a>
            </li>

    
        <!-- Navbar dropdown -->
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle text-warning"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Account
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    
            <li>
              <a class="dropdown-item" href="#">Password</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Profile</a>
            </li>
          </ul>
        </li>
  
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
    <!-- Navbar -->

  </header>
   <!-- Background image -->
   <div
   class="p-5 text-center bg-image"
   style="
   background-image: url('{%  static "hotel/img/logo10.jpg" %}');
     height: 400px;
   "
 >
   <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
     <div class="d-flex justify-content-center align-items-center h-100">
       <div class="text-white">
         <h1 class="mb-3">ANNOUNCEMENT SYSTEM </h1>
         <h4 class="mb-3">Dodoma TZ</h4>
         <a class="btn btn-outline-light btn-lg" href="" role="button"
         >ONLINE APPLICATION IS OPENED</a
         >
       </div>
     </div>
   </div>
 </div>
 <!-- Background image -->
 <body style="background-color: #BED9F7;"> 
{% block content%}



{% endblock %}

</body>
 
<!-- Footer -->
<footer class="text-center text-lg-start bg-white text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
    
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3 text-secondary"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3 text-secondary"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3 text-secondary"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3 text-secondary"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

hotel/templates/hotel/hotel_form.html
{% extends 'hotel/base.html' %}

{% block content %}
<h1>Add Hotel</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

hotel/templates/hotel/hotel_list.html
{% extends 'hotel/base.html' %}

{% block content %}
<h1>Hotel List</h1>

<ul>
    {% for hotel in hotels %}
        <li>{{ hotel.name }} - {{ hotel.location }}</li>
    {% endfor %}
</ul>
<a href="{% url 'hotel:create_hotel' %}">Add Hotel</a>
{% endblock %}